# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks


command=/usr/lib/i3blocks/$BLOCK_NAME/$BLOCK_NAME

# Global properties
separator=true
separator_block_width=20



# [volume]
# label=VOL
# instance=Master
# interval=once
# signal=10
# 
# [disk]
# label=home/:
# interval=30

[greetings]
command=echo "Welcome $USER"
interval=once

[arch-update]
markup=pango
interval=3600
#  QUIET=true
#WATCH=^linux.* ^pacman.*
#BASE_COLOR=#5fff5f
#UPDATE_COLOR=#FFFF85
#AUR=true
label=Updates:  


[time]
command=date '+%Y-%m-%d %H:%M:%S'
interval=1

[separator]

[usb]
markup=pango
IGNORE_LIST=["nvme0n1p3"]
signal=1
interval=10

[memory]
label=⎀ 
interval=1

[wifi]
label= wlp4s0:      
INTERFACE=wlp4s0
interval=1

[iface]
color=#00ff00
interval=3600

[separator]

[essid]
command=essid
interval=60
INTERFACE=wlp4s0


# [disk]
# label=/home/pawel: 
# INSTANCE=$HOME 
# interval=30

[volume]
LABEL=♪ 
interval=10
signal=10
STEP=5%

[battery]
interval=10
label=⚡
BAT_NUMBER=0

[battery]
interval=10
label=⚡
BAT_NUMBER=1
