#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc config border_width	4 
bspc config window_gap          10

bspc config border_width	0
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

xsetroot -cursor_name left_ptr

#Set up second monitor:
if [[ $(xrandr -q | grep 'DP-1-0 connected') ]]; then	
	xrandr --output eDP-1 --primary --mode 2560x1440 --rotate normal --output DP-1-0 --mode 1920x1080 --rotate normal --above eDP-1
else
	xrandr --outup eDP-1 --primary mode 2560x1440 --rotate normal 
fi

bspc monitor eDP-1 -d 6 7 8 9 10  
bspc monitor DP-1-0 -d 1 2 3 4 5 

#AutoStart Application
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
#polybar &


sh ~/.config/polybar/launch.sh
